### ISSUE TITLE
[ERROR] Failed to convert event 77qwz7g10br2no message=Cannot read property 'methodName' of undefined, stack=TypeError: Cannot read property 'methodName' of undefined

### ISSUE THREAD

**Issue by husnialhamdani** [opsgy/falco-gke-audit-bridge#17]
Hi @steven166,

I'm suffering below issue while I'm trying to integrate it with my GKE platform,

```
falco-test-cluster-6g4rv falco-gke-audit-bridge error: Failed to convert event 77qwz7g10br2no message=Cannot read property 'methodName' of undefined, stack=TypeError: Cannot read property 'methodName' of undefined
falco-test-cluster-6g4rv falco-gke-audit-bridge     at AuditService.convertAuditEvent (/app/audit.service.js:162:45)
falco-test-cluster-6g4rv falco-gke-audit-bridge     at AuditService.handleMessage (/app/audit.service.js:118:45)
falco-test-cluster-6g4rv falco-gke-audit-bridge     at Array.<anonymous> (/app/audit.service.js:103:39)
falco-test-cluster-6g4rv falco-gke-audit-bridge     at Timeout.dequeue [as _onTimeout] (/app/node_modules/throttled-queue/throttled-queue.js:66:29)
falco-test-cluster-6g4rv falco-gke-audit-bridge     at ontimeout (timers.js:436:11)
falco-test-cluster-6g4rv falco-gke-audit-bridge     at tryOnTimeout (timers.js:300:5)
falco-test-cluster-6g4rv falco-gke-audit-bridge     at listOnTimeout (timers.js:263:5)
falco-test-cluster-6g4rv falco-gke-audit-bridge     at Timer.processTimers (timers.js:223:10)
```

**Comment by 8Qbit** [comment]
Hi @steven166,
I have the same issue. It started suddenly today without no apparent reason. Any idea why this might be happening.
